name: release

on:
  push:
    branches: [ master ]

jobs:
  overleaf:
    name: Release .zip file
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
          persist-credentials: false

      - name: Create templates
        run: python3 build_release.py

      - name: Install zip
        run: sudo apt install zip

      - name: Zip preamble folder
        run: zip -qq -r ./overleaf.zip ./preamble ./template_*.tex

      # https://github.community/t/how-can-i-set-an-expression-as-an-environment-variable-at-workflow-level/16516/6
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: v${{ steps.date.outputs.date }}
          release_name: Release ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false

      - name: Upload overleaf.zip
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./overleaf.zip
          asset_name: overleaf.zip
          asset_content_type: application/zip

  preamble_only:
    name: Update preamble-only branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
          persist-credentials: false

      - name: Deploy to preamble-only
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: preamble-only
          FOLDER: preamble
